web: true
string: true
chainBoots: true
chainLeggings: true
chainChestplate: true
chainHelmet: true
netherBrick: true
saddle: true
grass: true
mossStone: true
ice: true
mycelium: true
crackedStoneBricks: true
mossyStoneBricks: true
sand: true
clay: true
redApple: true
clayBlock: true
sponge: true
cocoaBeans: true
blackMusicDisc: true
brokenMusicDisc: true
cyanMusicDisc: true
forestGreenMusicDisc: true
goldMusicDisc: true
greenMusicDisc: true
orangeMusicDisc: true
purpleMusicDisc: true
redMusicDisc: true
whiteMusicDisc: true
blueMusicDisc: true
stick: true
wood: true
glowstoneDust: true
fern: true
vines: true
lilyPad: true
tallGrass: true
ironOre: true
goldOre: true
redstoneOre: true
lapisOre: true
coalOre: true
diamondOre: true
diamond: true
blazeRod: true
slimeball: true
ghastTear: true
netherWart: true
gunpowder: true
enderPearl: true
monsterEgg: true
arrowToStick: true
diamond: true